Repository andela/ah-frontend-invictus, pull requests merged in 2019-06, with the labels that each got.

#18 chore(app-structure): Add app structure
  package-lock.json
  src/Router.js
  src/app/Login/__tests__/Login.test.js
  src/app/__tests__/App.test.js
  src/app/__tests__/Hoc.test.js
  src/app/__tests__/Home.test.js
  src/app/__tests__/Login.test.js
  src/app/__tests__/__snapshots__/App.test.js.snap
  src/app/__tests__/__snapshots__/Hoc.test.js.snap
  src/app/__tests__/__snapshots__/Home.test.js.snap
  src/app/__tests__/__snapshots__/Login.test.js.snap
  src/app/components/components.txt
  src/app/containers/Home.jsx
  src/app/containers/Login.jsx
  src/app/hoc/Aux.js
  src/redux/actions/types.js
  src/redux/indexReducer.js
  src/redux/reducers/reducers.txt
Labels: ready for review

#13 #165273432 User should be able to reset a password
  app.json
  package-lock.json
  package.json
  src/App.scss
  src/Router.js
  src/app/__tests__/__snapshots__/resetPasswordComponent.test.js.snap
  src/app/__tests__/__snapshots__/resetPasswordContainer.test.js.snap
  src/app/__tests__/resetPasswordAction.test.js
  src/app/__tests__/resetPasswordComponent.test.js
  src/app/__tests__/resetPasswordContainer.test.js
  src/app/__tests__/resetPasswordReducer.test.js
  src/app/components/PasswordResetForm.jsx
  src/app/components/components.txt
  src/app/containers/Errors.jsx
  src/app/containers/ResetPassword/RequestResetPassword.jsx
  src/app/containers/ResetPassword/ResetPassword.jsx
  src/app/containers/ResetPassword/util.js
  src/app/mock_data.js
  src/app/utils.js
  src/index.scss
  src/redux/actions/resetPasswordAction.js
  src/redux/actions/types.js
  src/redux/indexReducer.js
  src/redux/reducers/reducers.txt
  src/redux/reducers/resetPasswordReducer.js
  src/redux/rootReducer.js
  src/utilities.js
Labels: ready for review

#17 feat(post article): Add create article
  .eslintignore
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/Router.js
  src/app/__tests__/ArticleActions.test.js
  src/app/__tests__/ArticleComponent.test.js
  src/app/__tests__/ArticleContainer.test.js
  src/app/__tests__/ArticleReducer.test.js
  src/app/__tests__/__snapshots__/App.test.js.snap
  src/app/__tests__/__snapshots__/ArticleContainer.test.js.snap
  src/app/components/ArticleComponent.jsx
  src/app/components/PasswordResetForm.jsx
  src/app/containers/ArticleContainer.js
  src/app/utils.js
  src/assets/styles/article.scss
  src/assets/styles/resetpassword.scss
  src/redux/actions/ArticleActions.js
  src/redux/actions/types.js
  src/redux/reducers/ArticleReducer.js
  src/redux/rootReducer.js
  src/redux/store.js
Labels: ready for review

#21 Add social authentication
  .travis.yml
  package-lock.json
  package.json
  public/index.html
  src/app/__mocks__/mockLocalStorage.js
  src/app/__tests__/Login.test.js
  src/app/__tests__/Login/__snapshots__/component.test.js.snap
  src/app/__tests__/Login/__snapshots__/container.test.js.snap
  src/app/__tests__/Login/component.test.js
  src/app/__tests__/Login/container.test.js
  src/app/__tests__/SocialAuthTests/__snapshots__/containers.test.js.snap
  src/app/__tests__/SocialAuthTests/actions.test.js
  src/app/__tests__/SocialAuthTests/containers.test.js
  src/app/__tests__/__snapshots__/Login.test.js.snap
  src/app/__tests__/__snapshots__/Signup.test.js.snap
  src/app/components/Login.jsx
  src/app/components/Signup.jsx
  src/app/containers/Login.jsx
  src/app/containers/SocialAuth.jsx
  src/app/urls.js
  src/assets/images/iconfinder_facebook_313103.png
  src/assets/styles/_var.scss
  src/assets/styles/app.scss
  src/assets/styles/login.scss
  src/assets/styles/socialbuttons.scss
  src/redux/actions/socialAuth/socialAuthAction.js
  src/redux/actions/types.js
  src/redux/reducers/socialAuth.js
  src/redux/rootReducer.js
Labels: finished

#16 #165273435 users should be able to view and edit their profile
  package-lock.json
  package.json
  src/App.js
  src/Router.js
  src/app/__tests__/Login/__snapshots__/Home.test.js.snap
  src/app/__tests__/__snapshots__/App.test.js.snap
  src/app/__tests__/__snapshots__/router.test.js.snap
  src/app/__tests__/navbar.test.js
  src/app/__tests__/router.test.js
  src/app/__tests__/userProfileTests/__snapshots__/articleComponent.test.js.snap
  src/app/__tests__/userProfileTests/__snapshots__/edit.test.js.snap
  src/app/__tests__/userProfileTests/__snapshots__/profileComponent.test.js.snap
  src/app/__tests__/userProfileTests/__snapshots__/profileContainer.test.js.snap
  src/app/__tests__/userProfileTests/__snapshots__/spinner.test.js.snap
  src/app/__tests__/userProfileTests/articleComponent.test.js
  src/app/__tests__/userProfileTests/edit.test.js
  src/app/__tests__/userProfileTests/profileAction.test.js
  src/app/__tests__/userProfileTests/profileComponent.test.js
  src/app/__tests__/userProfileTests/profileContainer.test.js
  src/app/__tests__/userProfileTests/profileReducer.test.js
  src/app/__tests__/userProfileTests/spinner.test.js
  src/app/components/Navbar.jsx
  src/app/components/ProfileArticleComponent.jsx
  src/app/components/ProfileComponent.jsx
  src/app/components/SpinnerComponent.jsx
  src/app/containers/ProfileContainer.jsx
  src/app/containers/editProfileContainer.jsx
  src/assets/images/avatar2.png
  src/assets/images/edna.jpg
  src/assets/images/profile.jpeg
  src/assets/styles/_var.scss
  src/assets/styles/spinner.scss
  src/assets/styles/userprofile.scss
  src/firebase/config.js
  src/redux/actions/LoginActions.js
  src/redux/actions/profileActions.js
  src/redux/actions/types.js
  src/redux/reducers/profileReducer.js
  src/redux/rootReducer.js
  src/redux/store.js
Labels: ready for review

#26 #166492273 Read Articles
  src/Router.js
  src/app/__tests__/Login/__snapshots__/Home.test.js.snap
  src/app/__tests__/__snapshots__/router.test.js.snap
  src/app/__tests__/articles/__snapshots__/articleComponent.test.js.snap
  src/app/__tests__/articles/__snapshots__/articleContainer.test.js.snap
  src/app/__tests__/articles/__snapshots__/articlesComponent.test.js.snap
  src/app/__tests__/articles/__snapshots__/articlesContainer.test.js.snap
  src/app/__tests__/articles/articleActions.test.js
  src/app/__tests__/articles/articleComponent.test.js
  src/app/__tests__/articles/articleContainer.test.js
  src/app/__tests__/articles/articleReducers.test.js
  src/app/__tests__/articles/articlesActions.test.js
  src/app/__tests__/articles/articlesComponent.test.js
  src/app/__tests__/articles/articlesContainer.test.js
  src/app/__tests__/articles/articlesReducers.test.js
  src/app/components/Home.jsx
  src/app/components/Navbar.jsx
  src/app/components/articles/ArticlesComponent.jsx
  src/app/components/articles/getArticleComponent.jsx
  src/app/containers/SocialAuth.jsx
  src/app/containers/articles/ArticlesContainer.jsx
  src/app/containers/articles/getArticleContainer.jsx
  src/app/urls.js
  src/assets/images/aerial-shot.jpg
  src/assets/images/edna.jpg
  src/assets/styles/_var.scss
  src/assets/styles/articles.scss
  src/redux/actions/articles/ArticleActions.js
  src/redux/actions/articles/ArticlesActions.js
  src/redux/actions/types.js
  src/redux/reducers/ArticlesReducer.js
  src/redux/reducers/getArticleReducer.js
  src/redux/rootReducer.js
Labels: ready for review

#24 #165273442 A user should be able to like dislike articles
  public/index.html
  src/app/__tests__/ArticleActions.test.js
  src/app/__tests__/LikeArticleActions.test.js
  src/app/__tests__/LikeArticleReducer.test.js
  src/app/__tests__/articles/__snapshots__/articleComponent.test.js.snap
  src/app/__tests__/articles/__snapshots__/articleContainer.test.js.snap
  src/app/__tests__/articles/__snapshots__/articlesComponent.test.js.snap
  src/app/__tests__/articles/articleContainer.test.js
  src/app/__tests__/dislikeArticleActions.test.js
  src/app/__tests__/dislikeArticleReducers.test.js
  src/app/components/AricleLike.jsx
  src/app/components/articles/ArticlesComponent.jsx
  src/app/components/articles/getArticleComponent.jsx
  src/app/containers/ArticleContainer.js
  src/app/containers/articles/getArticleContainer.jsx
  src/app/utils.js
  src/assets/styles/_var.scss
  src/assets/styles/articles.scss
  src/redux/actions/ArticleActions.js
  src/redux/actions/types.js
  src/redux/reducers/dislikeArticleReducers.js
  src/redux/reducers/likeArticleReducers.js
  src/redux/rootReducer.js
Labels: ready for review

#27 #165273443 tags should be visible in all views
  package-lock.json
  package.json
  public/index.html
  src/Router.js
  src/app/__tests__/ArticleContainer.test.js
  src/app/__tests__/__snapshots__/ArticleContainer.test.js.snap
  src/app/__tests__/__snapshots__/router.test.js.snap
  src/app/__tests__/articles/__snapshots__/articleComponent.test.js.snap
  src/app/__tests__/articles/__snapshots__/articlesComponent.test.js.snap
  src/app/__tests__/articles/articleComponent.test.js
  src/app/__tests__/articles/articlesComponent.test.js
  src/app/components/ArticleComponent.jsx
  src/app/components/Login.jsx
  src/app/components/articles/ArticlesComponent.jsx
  src/app/components/articles/getArticleComponent.jsx
  src/app/containers/ArticleContainer.js
  src/assets/styles/_var.scss
  src/assets/styles/articles.scss
  src/redux/actions/ArticleActions.js
Labels: ready for review

#29 #166377934 Write a descriptive readme
  README.md
  src/app/components/AricleLike.jsx
  src/assets/images/SignUp.png
  src/assets/images/createArticle.png
  src/assets/images/likeArticle.png
  src/assets/images/logIn.png
  src/assets/images/readArticles.png
Labels: ready for review

#22 #165273440 Add timestamped comments to any article.
  .eslintrc
  src/app/__tests__/SocialAuthTests/reducer.test.js
  src/app/__tests__/articles/__snapshots__/articleComponent.test.js.snap
  src/app/__tests__/comments/__snapshots__/commentContainer.test.js.snap
  src/app/__tests__/comments/__snapshots__/component.test.js.snap
  src/app/__tests__/comments/__snapshots__/fetchComponent.test.js.snap
  src/app/__tests__/comments/commentAction.test.js
  src/app/__tests__/comments/commentContainer.test.js
  src/app/__tests__/comments/commentReducer.test.js
  src/app/__tests__/comments/component.test.js
  src/app/__tests__/comments/fetchCommentAction.test.js
  src/app/__tests__/comments/fetchComponent.test.js
  src/app/__tests__/comments/fetchReducer.test 2.js
  src/app/__tests__/comments/fetchReducer.test.js
  src/app/components/Comment.jsx
  src/app/components/FetchComment.js
  src/app/components/articles/ArticlesComponent.jsx
  src/app/components/articles/getArticleComponent.jsx
  src/app/containers/CommentContainer.js
  src/app/containers/articles/getArticleContainer.jsx
  src/assets/styles/fetchcomment 2.scss
  src/assets/styles/fetchcomment.scss
  src/assets/styles/login.scss
  src/redux/actions/CommentAction.js
  src/redux/actions/FetchCommentAction.js
  src/redux/actions/commentUrl.js
  src/redux/actions/types.js
  src/redux/reducers/CommentReducer.js
  src/redux/reducers/FetchCommentReducer.js
  src/redux/rootReducer.js
Labels: Ready for merge

#23 #165273439 Users should be able to rate articles and view article ratings
  package-lock.json
  src/app/__tests__/RateAticles/RateArticleAction.test.js
  src/app/__tests__/RateAticles/RateArticleContainer.test.js
  src/app/__tests__/articles/__snapshots__/articlesComponent.test.js.snap
  src/app/__tests__/articles/articleActions.test.js
  src/app/__tests__/resetPassword/__snapshots__/resetPasswordComponent.test.js.snap
  src/app/__tests__/resetPassword/__snapshots__/resetPasswordContainer.test.js.snap
  src/app/__tests__/resetPassword/resetPasswordAction.test.js
  src/app/__tests__/resetPassword/resetPasswordComponent.test.js
  src/app/__tests__/resetPassword/resetPasswordContainer.test.js
  src/app/__tests__/resetPassword/resetPasswordReducer.test.js
  src/app/components/articles/ArticlesComponent.jsx
  src/app/components/articles/getArticleComponent.jsx
  src/app/containers/Errors.jsx
  src/app/containers/RateArticle.jsx
  src/app/containers/ResetPassword/RequestResetPassword.jsx
  src/app/containers/ResetPassword/ResetPassword.jsx
  src/app/containers/articles/getArticleContainer.jsx
  src/app/containers/rateArticleUtil.js
  src/assets/styles/rateArticle.scss
  src/redux/actions/ArticleActions.js
  src/redux/actions/RateArticleAction.js
  src/redux/actions/articles/ArticleActions.js
  src/redux/actions/types.js
  src/redux/reducers/rateArticle.js
  src/redux/rootReducer.js
Labels: Ready for merge

#25 ft(update and delete article): Update delete article feature
  src/Router.js
  src/app/__tests__/UpdateArticleAction.test.js
  src/app/__tests__/UpdateArticleComponent.test.js
  src/app/__tests__/UpdateArticleContainer.test.js
  src/app/__tests__/UpdateArticleReducer.test.js
  src/app/__tests__/__snapshots__/UpdateArticleComponent.test.js.snap
  src/app/__tests__/__snapshots__/UpdateArticleContainer.test.js.snap
  src/app/__tests__/__snapshots__/router.test.js.snap
  src/app/__tests__/articles/DeleteArticleAction.test.js
  src/app/__tests__/articles/DeleteArticleComponent.test.js
  src/app/__tests__/articles/DeleteArticleContainer.test.js
  src/app/__tests__/articles/DeleteArticleReducer.test.js
  src/app/__tests__/articles/__snapshots__/DeleteArticleComponent.test.js.snap
  src/app/__tests__/articles/__snapshots__/DeleteArticleContainer.test.js.snap
  src/app/__tests__/articles/__snapshots__/articleComponent.test.js.snap
  src/app/__tests__/articles/articleComponent.test.js
  src/app/__tests__/articles/articleContainer.test.js
  src/app/components/DeleteArticle.jsx
  src/app/components/Signup.jsx
  src/app/components/UpdateArticle.jsx
  src/app/components/articles/getArticleComponent.jsx
  src/app/containers/DeleteArticle.jsx
  src/app/containers/UpdateArticle.jsx
  src/app/containers/articles/getArticleContainer.jsx
  src/assets/styles/getarticle.scss
  src/assets/styles/updatearticle.scss
  src/redux/actions/DeleteArticle.js
  src/redux/actions/UpdateArticle.js
  src/redux/actions/types.js
  src/redux/reducers/DeleteArticle.js
  src/redux/reducers/UpdateArticle.js
  src/redux/rootReducer.js
  src/redux/store.js
Labels: ready for review

#32 #165273459 enable users to bookmark articles
  README.md
  package-lock.json
  src/app/__tests__/articles/__snapshots__/articleComponent.test.js.snap
  src/app/__tests__/articles/__snapshots__/articleContainer.test.js.snap
  src/app/__tests__/articles/articleContainer.test.js
  src/app/__tests__/bookmarks/bookmarkActions.test.js
  src/app/__tests__/bookmarks/bookmarkReducers.test.js
  src/app/components/articles/getArticleComponent.jsx
  src/app/containers/articles/getArticleContainer.jsx
  src/redux/actions/ArticleActions.js
  src/redux/actions/types.js
  src/redux/reducers/BookmarksReducer.js
  src/redux/rootReducer.js
Labels: Ready for merge

#33 #165273444 User should be able to share articles on social media.
  .travis.yml
  package-lock.json
  package.json
  src/app/__tests__/ShareArticle.test.js
  src/app/__tests__/__snapshots__/ShareArticle.test.js.snap
  src/app/__tests__/articles/__snapshots__/articleComponent.test.js.snap
  src/app/__tests__/articles/articleComponent.test.js
  src/app/__tests__/articles/articleComponent.test.js.snap
  src/app/__tests__/resetPassword/resetPasswordReducer.test.js
  src/app/components/ShareArticle.jsx
  src/app/components/articles/getArticleComponent.jsx
  src/assets/styles/shareArticleButtons.scss
Labels: Ready for merge

#35 #165273448 Users should be able to search and filter art…
  src/Router.js
  src/app/__tests__/__snapshots__/navbar.test.js.snap
  src/app/__tests__/__snapshots__/router.test.js.snap
  src/app/__tests__/search/__snapshots__/searchComponent.test.js.snap
  src/app/__tests__/search/__snapshots__/searchContainer.test.js.snap
  src/app/__tests__/search/searchAction.test.js
  src/app/__tests__/search/searchComponent.test.js
  src/app/__tests__/search/searchContainer.test.js
  src/app/__tests__/search/searchReducer.test.js
  src/app/components/Navbar.jsx
  src/app/components/SearchComponent.jsx
  src/app/containers/Search.jsx
  src/redux/actions/searchActions.js
  src/redux/actions/types.js
  src/redux/reducers/Search.js
  src/redux/rootReducer.js
Labels: ready for review

#36 #165273441 Add pagination support
  src/app/__tests__/articles/__snapshots__/articlesComponent.test.js.snap
  src/app/__tests__/articles/__snapshots__/paginationComponent.test.js.snap
  src/app/__tests__/articles/articlesComponent.test.js
  src/app/__tests__/articles/paginationComponent.test.js
  src/app/components/Pagination.jsx
  src/app/components/articles/ArticlesComponent.jsx
  src/assets/styles/articles.scss
  src/redux/reducers/ArticlesReducer.js
Labels: Ready for merge
